sudo: required
language: python
python:
  - '2.7'
before_install:
  - docker run -d --hostname rabbitmq --name rabbitmq -p 15672:15672 -p 5672:5672 -e RABBITMQ_DEFAULT_USER=guest -e RABBITMQ_DEFAULT_PASS=guest rabbitmq:3.5.4-management
services:
  - docker
install:
  - pip install tox
env:
  - TOX_ENV=py27-lib
  - TOX_ENV=py33-lib
  - TOX_ENV=py34-lib
  - TOX_ENV=py34-examples
script:
  - tox -e $TOX_ENV
